version: "3.9"
services:
  db:
    image: postgres:15.3
    volumes:
      - dbvolume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"

volumes:
  dbvolume:
