class Parser::TicketsWithTicketNumber < Parser::Csv
  def headers
    return [
    'Issuing Agency',
    'ticket_num',
    'Type',
    'Source',
    'violator type',
    'cdl',
    'class',
    'Event Date',
    'Time-HH',
    'Time-MM',
    'AM-PM',
    'Location ID',
    'Location Name',
    'Offense',
    'Offense Description',
    'posted speed',
    'violation speed',
    'posted',
    'radar',
    'clocked',
    'assessment',
    'Expected assessmnt',
    'display assessmnt',
    'disposition',
    'diposition desc',
    'criminial',
    'major indc',
    'sdip points',
    'surchargeable',
    'Race',
    'Sex',
    'vehicle color',
    'make',
    'model yr',
    '16 pass',
    'haz mat',
    'amount',
    'Paid',
    # 'hearing requested',
    'court code',
    'Age',
    'Searched'
    ]
  end
end
