<% require "dotenv"; Dotenv.load(".env") %>

# Name of your application. Used to uniquely configure containers.
service: window

# Name of the container image.
image: <%= ENV.fetch("DOCKER_IMAGE") %>

# Deploy to these servers.
servers:
  web:
    hosts:
      - <%= ENV.fetch('DEPLOY_SERVER') %>
    options:
      init: true

registry:
  server: registry.digitalocean.com
  username: <%= ENV.fetch("REGISTRY_USERNAME") %>
  password: <%= ENV.fetch("REGISTRY_PASSWORD") %>

accessories:
  db:
    image: postgres:15.3
    host: <%= ENV.fetch('DEPLOY_SERVER') %>
    port: 5432
    env:
      clear:
        POSTGRES_PASSWORD: <%= ENV.fetch('DATABASE_PASSWORD') %>
    volumes:
      - /pgdata:/var/lib/postgresql/data

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true

builder:
  arch: amd64
  context: "."
  args:
    RAILS_MASTER_KEY: <%= ENV.fetch("RAILS_MASTER_KEY") %>

proxy:
  hosts:
    - window.statereference.com
    - www.wokewindows.org
    - wokewindows.org
  app_port: 3000
  ssl: true
  ssl_redirect: true
  healthcheck:
    path: /up
    interval: 5
    timeout: 5
