ENTRIES = [
  # ["BARTLETT, Dorston", "9/25/20", xxx, "ABDW, False Police Report. Retired. SCDAO investigation/prosecution on-going. Co-D David Finnerty & Kenny Orcel."],
  # ["BROWN, Leonard F", "9/25/20", xxx, "BPD internal investigation (conformance to laws). Resigned. Source: Boston Globe Public Records Request."],
  # ["CALLENDER, Grant E", "9/25/20", xxx, "BPD internal investigation (conformance to laws). Retired. Source: Boston Globe Public Records Request."],
  ["CARNES, James", "9/25/20", 10393, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  ["CLARK, James", "6/14/17", 11891, "Alleged Forgery/Uttering. Reported to BPD IAD & State Ethics Commission. "],
  ["COLUMBO, Domenic ", "9/25/20", 120929, "OUI-Serious Bodily Injury. SCDAO investigation/prosecution on-going. Incident: Jan. 1, 2018. Special ADA Greer Spatz."],
  ["CONWAY, Kendra", "9/25/20", 12282, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  ["CURTIS, Christopher", "9/25/20", 148253, "Witness intimidation, False Report, CORI Violation, Forgery, Uttering. SCDAO investigation/prosecution on-going. Incident 03/01/2019."],
  ["DANILECKI, John", "9/25/20", 8947, "Open BPD Internal Affairs investigations. Boston Globe 06/24/2020"],
  ["DePINA-COOLEY, Mila", "6/19/17", 12015, "Receiving stolen merchandise. SCDAO investigation/prosecution on-going."],
  # ["DIAZ, Edgar", "9/25/20", xxx, "BPD internal investigation (3 counts of conformance to laws). Retired. Source: Boston Globe Public Records Request."],
  ["DOHERTY, Henry", "9/25/20", 9726, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  ["DOHERTY, Michael", "9/25/20", 12202, "AB (2 counts), AB to Intimidate, Use without Authority. Aqcuited of Civil Rights Violation. 2018 SCDAO investigation/prosecution."],
  # ["FINNERTY, David", "9/25/20", xxx, "Accessory After ABDW, Filing False Police Report. Unpaid Admin. Leave. SCDAO investigation/prosecution on-going. Co-D Dorston Bartlett & Kenny Orcel."],
  ["FITZGERALD, Paul A", "9/25/20", 9732, "BPD internal investigation (conformance to laws). Retired. Source: Boston Globe Public Records Request."],
  ["FONSECA, Sandro", "9/25/20", 106710, "Assault with a dangerous weapon, carrying a firearm while intoxicated. SCDAO investigation/prosecution. Resolved in Veteran's Court. Incident 12/11/2013. Also, Sustained BPD internal investigation."],
  ["FRANKLIN, Korey", "9/25/20", 102951, "Misleading Investigators. SCDAO investigation/prosecution on-going."],
  # ["HANDLEMAN-SMITH, Anthony", "9/25/20", xxx, "BPD internal investigation (conformance to laws). Resigned. Source: Boston Globe Public Records Request. [SCDAO Non-Prosecution Agreement]"],
  ["HERRERA-BREA, Alexis", "9/25/20", 148270, "ABDW Family Member. SCDAO investigation/prosecution on-going. Incident 04/19/2020."],
  ["HESSE, Jarrett", "9/25/20", 136936, "Resigned during the pendancy of a 2017 BPD internal investigation."],
  # ["HOLLAND, Trent W.", "9/25/20", xxx, "BPD internal investigation (allegation conformance to laws). Retired. Source: Boston Globe Public Records Request."],
  ["HOSEIN, Haseeb", "9/25/20", 10273, "Internal Affairs investigation alleged corruption. Source: Commonwealth Magazine 09/20/2020."],
  # ["LACET, Jovan", "9/25/20", xxx, "Alleged perjury. BPD Spokesperson confirmed termination to Dorchester Reporter on  8/10/2016."],
  ["LOPEZ, Diana", "9/25/20", 9370, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  # ["LOPRIORE, Michael", "9/25/20", xxx, "Larceny. SCDAO investigation/prosecution. CWOF with case dismissed 01/29/2010"],
  ["LYNCH, Joseph", "9/25/20", 86180, "Alleged racial slurs (09/13/2019 noise complaint/Roxbury Prep students). SCDAO investigation on-going."],
  ["MARZANO, Frederick G.", "9/25/20", 10286, "BPD internal investigation (conformance to laws). Retired when charges pending. Source: Boston Globe 09/23/2020"],
  ["McCARTHY, Patrick J.", "9/25/20", 103766, "BPD internal investigation (conformance to laws). Separation Agreement. Source: Boston Globe Public Records Request."],
  ["McGOLDRICK, Patricia", "9/25/20", 10172, "BPD internal investigation (conformance to laws). Resigned. Source: Boston Globe Public Records Request."],
  ["MITCHELL-WILLIAMS, Angela", "9/25/20", 10603, "Improper firearm storage. SCDAO investigation/prosecution. Agreed-upon plea. Incident: 08/6/2015."],
  ["MORIARTY, Richard", "9/18/18", 11120, "Motion To Suppress (Judge Mary Ames Suffolk Superior Court decision)."],
  ["MURPHY, Michael", "9/25/20", 11906, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  ["NEE, Joseph", "9/25/20", 12132, "Larceny, money laundering. Joint investigation AGO/SCDAO/BPD Anti-Corruption. GJ Indictment 10/12/2017. CWOF - Dismissed."],
  ["NELSON, Ronald", "9/25/20", 8227, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  ["O'BRIEN, Gerard", "9/25/20", 10294, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  # ["O'DONNELL, Dale T", "6/19/17", xxx, "BPD internal investigation (allegation conformance to laws). Retired. Source: Boston Globe Public Records Request."],
  ["ODNEY, Eddie", "9/25/20", 81488, "Access device fraud. USAO investigation/prosecution. Guilty plea 08/09/2016."],
  # ["ORCEL, Kenny", "9/25/20", xxx, "Accessory After ABDW, Filing False Police Report. Terminated. SCDAO investigation/prosecution. Co-D Dorston Bartlett & David Finnerty."],
  # ["PHILLIPS, Junior A.", "9/25/20", xxx, "BPD internal investigation (conformance to laws). Resigned. Source: Boston Globe Public Records Request."],
  # ["ROBERTSON, William J.", "9/25/20", xxx, "BPD internal investigation (conformance to laws). Resigned. Source: Boston Globe Public Records Request. "],
  ["ROSE, Patrick", "9/25/20", 11126, "Aggravated Rape of Child, Rape of Child. SCDAO investigation/prosecution on-going."],
  # ["ROSENTHAL, Daniel J.", "9/25/20", xxx, "BPD internal investigation (allegation conformance to laws). Resigned. Source: Boston Globe Public Records Request."],
  ["SCANTLEBURY, Vaden", "9/25/20", 10970, "Alleged ABDW, Witness Intimidation, Perjury. SCDAO investigation on-going."],
  ["SMIGIELSKI, Brian", "10/5/15", 11530, "USAO investigation/prosecution. Guilty plea. Sentence on 01/28/2016."],
  # ["STEELE, Mel", "10/17/14", xxx, "USAO investigation/prosecution. Guilty plea. Sentenced on 01/20/2015."],
  ["STINSON, Monicka", "9/25/20", 103868, "Witness intimidation. SCDAO investigation/prosectution on-going."],
  ["SULLIVAN, Ryan P", "9/25/20", 135938, "BPD internal investigation (conformance to laws). Resigned. Source: Boston Globe Public Records Request."],
  ["TORIGIAN, Timothy", "9/25/20", 9807, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  # ["TULLY, Robert M", "9/25/20", xxx, "BPD internal investigation (conformance to laws). Retired. Source: Boston Globe Public Records Request."],
  ["TWITCHELL, Robert", "9/25/20", 10093, "Conspiracy/embezzlement: Time & attendance. USAO prosecution on-going."],
  # ["VEAL, Royce", "9/25/20", xxx, "BPD internal investigation (conformance to laws). Resigned. Source: Boston Globe Public Records Request. [SCDAO Non-Prosecution Agreement]"],
  ["WALSH, Emmet T.", "9/25/20", 10327, "BPD internal investigation (conformance to laws). Retired when charges pending. Source: Boston Globe 09/23/2020"],
  # ["WARREN, Robert G.", "9/25/20", xxx, "BPD internal investigation (conformance to laws). Retired. Source: Boston Globe Public Records Request."],
  ["WOODLEY, William", "9/25/20", 8195, "Larceny: Time & attendance/overtime. SCDAO investigation/prosecution. CWOF - Dismissed."],
]

ENTRIES.each do |name, date_added, emp_no, lead_entry|
  o = Officer.find_by(employee_id: emp_no)
  o.lead_entry = lead_entry
  o.lead_added = Chronic.parse(date_added).strftime("%F")
  o.save!
end
